name: Build and Commit PDF

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX environment
      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk

      # Step 3: Compile LaTeX to PDF
      - name: Compile LaTeX document
        run: latexmk -pdf -interaction=nonstopmode -output-directory=output Arash-Sarshar-CV.tex

      # Step 4: Commit the PDF to the repository
      - name: Commit and Push PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          cp output/Arash-Sarshar-CV.pdf .
          git add Arash-Sarshar-CV.pdf
          git commit -m "Automated PDF update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token
